manifest.json, popup.html, popup.js, scripts/baekjoon/baekjoon.js, scripts/baekjoon/parsing.js, scripts/baekjoon/variables.js, scripts/util.js, welcome.html
- 일부 오타 수정
- 홈 화면의 하단 element 중앙 정렬
- popup js 아이콘 title 추가(마우스 올리면 텍스트 나오도록)
- 패치노트 아이콘으로 변경
- 서브태스크는 '맞았습니다!!' 대신 '100점'이라고 처리되는점 고려
- 맞은 케이스 배열로 관리하여 include()문으로 처리
=> Bjac 18 - UI 개선, 서브태스크 처리 기능 추가

scripts/baekjoon/parsing.js
=> Fix 제출 테이블 상황에 따라 자신의 제출 목록만을 파싱하도록 수정 

scripts/baekjoon/uploadfunctions.js
=> Fix 전체 코드 업로드 시, 더미 데이터가 들어오지 않도록 예외처리

scripts/baekjoon/baekjoon.js, scripts/baekjoon/parsing.js
- 문제 제출 url에서 로더 시작 규칙 정정과 백준 사이트 로그인 시에만 동작하도록 로직 처리
- 문제 내에 problem_input, problem_output이 존재하지 않는 경우에도 정상적으로 업로드 가능하도록 처리
=> Fix 백준 내의 로더 시작 규칙과 입출력 예시가 없는 경우 파싱 에러 오류 수정

scripts/baekjoon/parsing.js, scripts/programmers/parsing.js, scripts/programmers/programmers.js, scripts/programmers/util.js, scripts/programmers/variables.js, scripts/storage.js
- 프로그래머스 문제를 기존 알고리즘 구분으로 업로드하던 경로를 백준과 동일하게 레벨별로 올리도록 수정하였습니다.
- 이슈 #88 에 해당하는 이미지 깨짐 현상을 제거하기 위해 src 속성값을 절대경로로 바꾸어주는 코드를 추가하였습니다.
=> Feat 프로그래머스 경로 구분을 알고리즘에서 레벨별로 올리도록 추가

manifest.json, scripts/baekjoon/baekjoon.js, scripts/baekjoon/parsing.js, scripts/baekjoon/util.js
- manifest의 매칭 사이트를 백준 사이트 전역으로 처리했습니다.
- 페이지를 코드 페이지로 옮겨서 업로드 처리를 했습니다.
- 문제 설명 및 요약 줄을 삭제하였습니다.
=> Hotfix 사이트 파싱 실패에 따른 오류 로직 변경 처리

scripts/baekjoon/baekjoon.js
#95 번 이슈 대응, url 체크에 대해 조건을 강화하였습니다.
=> Fix 채점 현황에 대한 url 조건 체크 강화 수정

manifest.json, scripts/Github.js, scripts/storage.js
=> Fix updateLocalStorageStats 함수 과정에서 tree가 존재하지 않는 경우의 예외처리 추가

.all-contributorsrc, README.md
* docs: update README.md [skip ci]
* docs: update .all-contributorsrc [skip ci]
=> Docs add doxxx93 as a contributor

scripts/baekjoon/parsing.js
대회코드로 판단되는 문제에 대해 에러를 던져 모달창에 표시
=> [Fix] 대회코드 업로드 방지 에러 추가

scripts/programmers/parsing.js
파일 저장이 .python3 이런식으로 되는거 같아서.. 혹시 .py와 같이 저장되도록 파싱하는 부분을 바꾸도록 수정해봤는데 수정 가능할까요?
=> Fix 저장되는 파일형식 수정

.all-contributorsrc, README.md
=> Docs add keinetwork as a contributor (#128) 

.all-contributorsrc, README.md
Reverts BaekjoonHub/BaekjoonHub#129
=> Revert "Docs add keinetwork as a contributor (#128) "

.all-contributorsrc, README.md
Reverts BaekjoonHub/BaekjoonHub#130
=> Revert "Revert "Docs add keinetwork as a contributor (#128) ""

manifest.json, scripts/baekjoon/baekjoon.js
=> Fix 백준의 제출 모달창이 업로드 도중에 꺼지는 문제 해결

manifest.json, scripts/baekjoon/util.js, scripts/swexpertacademy/parsing.js
- Fix 이미지 경로를 절대 경로로 바꿀 시 document 호출이 안되는 경우 예외처리
- Fix cEditor 내의 변경된 정보를 textSource에 업데이트 하도록 수정 (#135)
=> Fix 백준 이미지 경로 정정 오류와 프로그래머스 이전 소스코드 제출 오류 수정 (#135)

scripts/baekjoon/parsing.js, scripts/baekjoon/util.js, scripts/util.js
백준 사이트의 서브태스크가 있는 문제의 경우 부분 점수를 고려하지 않았던 오류를 수정해 높은 점수를 받은 답안이 푸쉬되도록 수정했습니다.
추가로, 서브태스크의 문제의 경우 커밋 메시지에 점수까지 포함되도록 수정했습니다.
관련 오류 : #189
=> Fix: baekjoon subtask upload issue (#189)

scripts/background.js
only tiny modify  background.js line 38  true --> false
=> modify background.js

scripts/baekjoon/parsing.js, scripts/programmers/parsing.js, scripts/storage.js, scripts/swexpertacademy/parsing.js, welcome.html, welcome.js
#231  에 나눴던 의견을 수용하여 변경 했습니다.
-  레파지토리 등록시 폴더 생성 옵션을 드롭다운으로 추가했습니다. 
- 기존 작동 방식을 유지하기 위해 로컬 스토리지에 "BaekjoonHub_OrgOption" 에 유효한 값이 존재 하지 않을 경우 자동적으로 "platform"으로 할당됩니다. 즉 기존 작동 방식은 "plaftorm"으로 정의 했습니다.
- #231 에서 "언급되었던 언어별 네이밍 규칙 첫글자 대문자 나머지 소문자로 바뀝니다. { JAVA -> Java } "는  "Organize by Language" 옵션 선택시에만 적용되는 문제이므로 작업 내용을 분리의 필요성이 없다고 생각해 유지합니다.
=> feat : 폴더 정리 옵션 드롭다운 추가

scripts/baekjoon/util.js
#240  #243 이슈 대응으로 다음과 같이 PR 신청합니다.
=> fix: 백준 문제 제출 시 시간 포멧팅이 잘못 나오는 오류 수정

scripts/programmers/util.js
#243  이슈 해결 과정에서 파생된 [문제](https://github.com/BaekjoonHub/BaekjoonHub/issues/243#issuecomment-1954005650)를 해결하였습니다.
#246 수정 과정에서 커밋 메시지가 삭제되지 않은 부분을 수정했습니다.
=> fix: 커밋 메시지 삭제

scripts/baekjoon/baekjoon.js, scripts/baekjoon/parsing.js, scripts/util.js
* 코드 길이가 비공개인 문제의 코드의 길이를 수동으로 계산하여 전처리 하였습니다.
- 14935, 1402번 문제 정상 커밋 확인
* * *
* 알고리즘 분류가 비어있는 문제는 '분류 없음'이 입력되도록 전처리 하였습니다.
- 9987, 16850, 4322, 13845번 문제 정상 커밋 확인
* * *
* 커밋 이상 없는 문제들 (백준에서 문제의 알고리즘 분류가 추가된 것으로 추정)
- 16019, 12261, 16461번 문제
* * *
해당 문제들 백준허브를 통해 커밋한 리포지토리 입니다
https://github.com/medAndro/BaekjoonHubTest
=> fix: 백준 문제의 bojData가 일부 비어있는 경우 커밋 실패 수정

.prettierignore, LICENSE, README.md, package.json
---
name: Pull Request
about: README, prettier settings
title: 'update readme and prettier'
labels: 'chore'
assignees: 'NERDHEAD-lb'
---
(여기에 PR에 포함된 주요 변경 사항들을 논리적인 단위로 나누어 요약해주세요. 각 변경 사항 아래에 관련 커밋들을 나열할 수 있습니다.)
- bd87693 - docs: README.md 정상화
- 의도와 다르게 표시되는 목차 수정
- img에 기본적으로 alt를 포함하도록 수정
- 일부 이미지의 잘못된 src 경로 참조 정상화
- 본문에 명시된 LINCENSE가 실제로 없는 문제 수정
- commit: 143c497 - docs: README에서 참조하지만 누락된 LICENSE 추가 ( MIT )
- commit: 987c048 - chore: prettier 설정 표준화 ( format -> prettier )
- package.json의 script format -> prettier 변경
- prettier 적용 대상 범위 확장
- .prettierignore 추가 및 선택적 제외 적용
=> update readme and prettier
